import { Feature } from  "./feature.entity"

export type UserFeatureQuota = Partial<Feature> & {
	feature_handle: string
	quota: number

	// generated by api
	remaining_quota?: number
	plan_quota?: number
}
